# Generated by Django 5.1.1 on 2024-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(),
        ),
    ]
