# Generated by Django 5.1.1 on 2024-11-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tag_alter_post_options_post_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="is_published",
            new_name="published",
        ),
    ]
