# Generated by Django 5.1.1 on 2024-11-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="blog.tag"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(),
        ),
    ]
