# Generated by Django 5.1.1 on 2024-11-29 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_tags_alter_post_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 29, 4, 25, 20, 811871, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
